environment: 'development'
name: RGBboy
paginate: 5
paginate_path: 'page-:num'
markdown: redcarpet
pygments: true
lessc: lessc
less_input_path: './less/style.less'
less_output_path: './_site/css/style.css'